export const POSTS = [
  {
    slug: 'vinted-tax-guide-uk-2025',
    title: 'The complete Vinted tax guide for UK resellers (2025)',
    excerpt: 'Everything you need to know about Vinted and HMRC — the £1,000 trading allowance, when you need to register, and how to file your self-assessment.',
    date: '2025-07-29',
    readTime: '8 min read',
    category: 'Tax',
    keywords: ['vinted tax guide', 'vinted tax UK', 'vinted HMRC', 'vinted self assessment', 'vinted £1000 trading allowance', 'vinted tax 2025', 'do i need to pay tax on vinted sales', 'vinted reseller tax UK'],
    author: 'Vintify Team',
    image: 'https://images.pexels.com/photos/6863245/pexels-photo-6863245.jpeg?auto=compress&cs=tinysrgb&w=1200',
    imageAlt: 'Tax documents and calculator on a desk',
    content: [
      { type: 'p', text: 'If you are selling on Vinted to make a profit, HMRC wants to know about it. The rules changed in 2024, and the thresholds for reporting are stricter than most people think. This guide covers everything you need to know to stay compliant without overpaying.' },
      { type: 'h2', text: 'The £1,000 trading allowance' },
      { type: 'p', text: 'Every UK individual gets a £1,000 trading allowance each tax year. If your total trading income (not profit — income) from all sources is under £1,000, you do not need to declare it or pay tax on it. But the moment you cross £1,000 in sales revenue, you must register for Self Assessment and report it.' },
      { type: 'p', text: 'Important: the £1,000 is income, not profit. If you bought items for £800 and sold them for £1,200, your income is £1,200 — you are over the threshold and must register, even though your profit is only £400.' },
      { type: 'h2', text: 'When you need to register for Self Assessment' },
      { type: 'p', text: 'You must register with HMRC by 5 October after the tax year in which you exceeded the £1,000 allowance. For example, if you crossed £1,000 in the 2024/25 tax year (ending 5 April 2025), you must register by 5 October 2025.' },
      { type: 'p', text: 'Registration is free and done online via gov.uk. You will get a Unique Taxpayer Reference (UTR) number, which you use to file your Self Assessment tax return each year.' },
      { type: 'h2', text: 'What counts as a business expense' },
      { type: 'p', text: 'You can deduct legitimate business expenses from your income before calculating profit. This reduces your tax bill legally. Common deductible expenses for Vinted resellers include:' },
      { type: 'ul', items: [
        'Cost of goods sold (what you paid for the items you are reselling)',
        'Packaging materials (poly bags, bubble wrap, tape, labels)',
        'Shipping costs not covered by the buyer',
        'Vintify subscription (software used for your business)',
        'Home office portion (a percentage of your internet, heating, and electricity if you work from home)',
        'Mileage for sourcing trips (45p per mile for the first 10,000 miles)',
      ]},
      { type: 'p', text: 'Keep receipts for everything. HMRC can ask for evidence up to 6 years after the tax year.' },
      { type: 'h2', text: 'How to calculate your profit' },
      { type: 'p', text: 'Your profit is your total sales income minus your total expenses. This is the figure you pay tax on, not your revenue. The tax rate depends on your total income from all sources:' },
      { type: 'ul', items: [
        'Personal allowance: £12,570 tax-free (2024/25)',
        'Basic rate: 20% on income between £12,571 and £50,270',
        'Higher rate: 40% on income between £50,271 and £125,140',
        'Additional rate: 45% on income above £125,140',
      ]},
      { type: 'p', text: 'If you have a day job earning £30,000 and make £5,000 profit from Vinted, your total income is £35,000 — all within the basic rate band, so you pay 20% on the Vinted profit (£1,000).' },
      { type: 'h2', text: 'How Vintify helps' },
      { type: 'p', text: 'Vintify automatically tracks your sales, fees, and shipping costs. You can log sourcing expenses and packaging costs as you go. At tax time, you export a single report with your total income, expenses, and profit — formatted to match what HMRC asks for on your Self Assessment. No spreadsheets, no manual entry, no missed receipts.' },
      { type: 'p', text: 'The £1,000 trading allowance is automatically calculated in the report, so you can see at a glance whether you need to file and exactly what figure to enter.' },
      { type: 'cta', text: 'Track your profit and generate HMRC-ready reports with Vintify', href: '/features/accounting' },
      { type: 'cta', text: 'Not sure if you need to register as a business seller? Read our Vinted Pro Seller guide', href: '/blog/vinted-pro-seller-guide' },
    ],
  },
  {
    slug: 'how-to-price-vinted-items',
    title: 'How to price your Vinted items for maximum profit',
    excerpt: 'Pricing is the single biggest lever in your reselling business. Here\'s a data-driven framework for pricing items that actually sell.',
    date: '2025-07-27',
    readTime: '6 min read',
    category: 'Growth',
    keywords: ['how to price vinted items', 'vinted pricing strategy', 'vinted pricing tips', 'how to price clothes for vinted', 'vinted pricing guide UK', 'vinted bundle pricing', 'vinted price drops'],
    author: 'Vintify Team',
    image: 'https://images.pexels.com/photos/19599223/pexels-photo-19599223.jpeg?auto=compress&cs=tinysrgb&w=1200',
    imageAlt: 'Clothes hanging on racks in a clothing store',
    content: [
      { type: 'p', text: 'Most resellers price by gut feeling. They look at what similar items are listed for, pick a number that feels right, and hope. This approach leaves money on the table — both from items priced too low and from items priced too high that never sell.' },
      { type: 'h2', text: 'The three factors that determine price' },
      { type: 'p', text: 'Every Vinted listing is worth exactly what a buyer will pay for it right now. That value is driven by three things:' },
      { type: 'ul', items: [
        'Brand demand — Nike, Zara, and Levi\'s sell faster than unknown brands at the same price',
        'Condition — "New with tags" commands a 30-50% premium over "Good used condition"',
        'Timing — Winter coats sell in October, not May. Swimwear sells in June, not November',
      ]},
      { type: 'h2', text: 'The cost-plus-floor method' },
      { type: 'p', text: 'Before you list, calculate your absolute floor price — the price below which you lose money. This is your cost price plus Vinted fees plus shipping plus packaging. If you bought a jacket for £8, Vinted takes £0.80 in fees (no seller fees since 2024, but buyer fees affect what they will pay), shipping is £2.99, and packaging is £0.30, your floor is £11.09.' },
      { type: 'p', text: 'Never list below your floor. If the market will not support your floor price, do not buy that item.' },
      { type: 'h2', text: 'The 30-day rule' },
      { type: 'p', text: 'List at your target price. If the item has not sold after 30 days, drop the price by 10%. After 60 days, drop another 10%. After 90 days, either drop to your floor price or delist and relist with new photos and a fresh listing.' },
      { type: 'p', text: 'Vintify automates this with auto price drops. You set the schedule once, and Vintify handles the reductions — no more checking listings every week.' },
      { type: 'h2', text: 'Psychological pricing on Vinted' },
      { type: 'p', text: 'Vinted buyers browse with filters. The most common price filters are rounded numbers — under £10, under £15, under £20. Pricing at £14.99 instead of £15.50 puts you in the "under £15" filter results, which dramatically increases visibility.' },
      { type: 'p', text: 'Similarly, pricing at £19.99 vs £22.00 moves you from the "under £20" filter to a less browsed tier. The 99p trick is not about psychology — it is about filter placement.' },
      { type: 'h2', text: 'Bundle pricing' },
      { type: 'p', text: 'Offer bundle discounts of 10-20% for buyers who purchase multiple items. This increases your average order value and clears slow-moving inventory. Vintify\'s bulk price editor lets you apply bundle discounts across hundreds of listings in seconds.' },
      { type: 'cta', text: 'Learn what brands and categories sell fastest on Vinted UK', href: '/blog/what-sells-best-on-vinted-uk' },
      { type: 'cta', text: 'Automate price drops and bundle discounts with Vintify', href: '/features/growth-bot' },
    ],
  },
  {
    slug: 'vinted-vs-depop-vs-ebay',
    title: 'Vinted vs Depop vs eBay: Which platform is best for resellers?',
    excerpt: 'We compare fees, audience, shipping, and seller experience across the three biggest resale platforms in the UK.',
    date: '2025-07-25',
    readTime: '10 min read',
    category: 'Guides',
    keywords: ['vinted vs depop', 'vinted vs ebay', 'vinted vs depop vs ebay', 'best reselling platform UK', 'vinted fees vs depop fees', 'vinted vs ebay fees', 'where to sell clothes UK'],
    author: 'Vintify Team',
    image: 'https://images.pexels.com/photos/6238363/pexels-photo-6238363.jpeg?auto=compress&cs=tinysrgb&w=1200',
    imageAlt: 'People shopping online together on a laptop',
    content: [
      { type: 'p', text: 'Choosing the right platform can double your sales or halve your profit. Each of the big three has distinct advantages and disadvantages depending on what you sell and how you operate.' },
      { type: 'h2', text: 'Fee structure' },
      { type: 'p', text: 'Vinted has zero seller fees. You list for free, sell for free, and keep 100% of the sale price. The buyer pays a small fee and shipping. This makes Vinted the most profitable platform per sale.' },
      { type: 'p', text: 'Depop charges 10% on every sale including shipping. Sell an item for £20 with £3 shipping, and Depop takes £2.30. eBay charges 10% on the item price (capped at £250 for most categories) plus 30p per listing if you exceed your monthly free allowance.' },
      { type: 'h2', text: 'Audience and what sells' },
      { type: 'p', text: 'Vinted skews heavily towards fashion — clothing, shoes, and accessories. The audience is primarily women aged 18-35 looking for bargains on mid-range brands. If you sell Nike, Zara, Levi\'s, or similar, Vinted is your best bet.' },
      { type: 'p', text: 'Depop has a younger audience (16-25) and leans towards streetwear, vintage, and Y2K fashion. Items that are trendy or unique perform better here. Expect more haggling and lower average sale prices.' },
      { type: 'p', text: 'eBay has the broadest audience and accepts almost anything. Electronics, homeware, car parts, collectables — eBay is the only platform where non-fashion items sell well. But the fees eat into your profit significantly.' },
      { type: 'h2', text: 'Shipping comparison' },
      { type: 'ul', items: [
        'Vinted: Integrated shipping with Evri, InPost, Yodel, and Royal Mail. Buyer chooses and pays. Seller just prints the label.',
        'Depop: Seller chooses shipping method. You can use Depop\'s integrated labels or arrange your own. More flexibility but more work.',
        'eBay: Seller sets shipping options and prices. Most sellers use eBay\'s integrated labels for tracked shipping.',
      ]},
      { type: 'p', text: 'Vinted\'s shipping is the simplest — the buyer selects and pays for shipping at checkout, and you just print the label. No calculating shipping costs or arguing with buyers about courier choice.' },
      { type: 'h2', text: 'Seller experience' },
      { type: 'p', text: 'Vinted is the easiest to list on — snap a photo, set a price, done. No complex listing forms or category trees. But the lack of seller tools means managing inventory at scale is painful without a tool like Vintify.' },
      { type: 'p', text: 'Depop has a social feed feel — buyers can follow you, like items, and message you. Building a following helps, but it requires consistent effort and engagement.' },
      { type: 'p', text: 'eBay has the most powerful seller tools — bulk listing, analytics, promoted listings, and a mature API. But the learning curve is steep, and the interface feels dated.' },
      { type: 'h2', text: 'The verdict' },
      { type: 'p', text: 'For fashion resellers in the UK, Vinted is the clear winner — zero fees, integrated shipping, and a large active buyer base. Use Depop for streetwear and vintage where the younger audience pays a premium. Use eBay for non-fashion items or when you need advanced selling tools.' },
      { type: 'p', text: 'The best resellers use all three — listing the same item on multiple platforms (with different prices to account for fees) and fulfilling wherever it sells first.' },
      { type: 'cta', text: 'New to Vinted? Start with our complete beginner\'s guide', href: '/blog/how-to-sell-on-vinted-uk-beginners-guide' },
      { type: 'cta', text: 'Compare all shipping options in our Vinted shipping guide', href: '/blog/vinted-shipping-guide' },
    ],
  },
  {
    slug: 'ai-listing-writer-guide',
    title: 'How AI listing writers work (and why they sell more)',
    excerpt: 'A deep dive into how Vintify\'s AI growth bot generates listings that rank in Vinted search and convert buyers.',
    date: '2025-07-23',
    readTime: '5 min read',
    category: 'Product',
    keywords: ['AI listing writer vinted', 'vinted AI listing tool', 'vinted listing description generator', 'AI vinted listings', 'vinted SEO listing', 'vinted listing tips', 'vinted hashtags'],
    author: 'Vintify Team',
    image: 'https://images.pexels.com/photos/16094040/pexels-photo-16094040.jpeg?auto=compress&cs=tinysrgb&w=1200',
    imageAlt: 'Person using a laptop with AI interface on screen',
    content: [
      { type: 'p', text: 'Writing a good Vinted listing takes 3-5 minutes per item. If you list 50 items a week, that is 4+ hours just writing descriptions. AI listing writers cut that to under 30 seconds per item — and the listings sell better.' },
      { type: 'h2', text: 'What makes a Vinted listing rank' },
      { type: 'p', text: 'Vinted search is keyword-based. When a buyer searches "Nike hoodie red," the algorithm looks for listings that contain all those words in the title and description. Most resellers write titles like "Nike hoodie" — missing the colour, size, and condition keywords that buyers actually search for.' },
      { type: 'p', text: 'A well-optimised title includes: brand, item type, colour, size, condition, and a key feature. For example: "Nike Tech Fleece Hoodie Red Size M Excellent Condition" instead of "Nike hoodie."' },
      { type: 'h2', text: 'How Vintify\'s AI writer works' },
      { type: 'p', text: 'You type a few words — "Nike hoodie red medium" — and Vintify generates a complete listing in seconds:' },
      { type: 'ul', items: [
        'SEO-optimised title with all relevant keywords',
        'Full description with measurements, condition notes, and styling suggestions',
        '8+ relevant hashtags for Vinted\'s tag-based discovery',
        'Suggested price based on recent sales of similar items',
      ]},
      { type: 'p', text: 'The AI is trained on thousands of successful Vinted listings, so it knows what language converts. It includes details buyers care about — pit-to-pit measurements, length, material composition — that most sellers skip.' },
      { type: 'h2', text: 'Why AI listings sell more' },
      { type: 'p', text: 'Listings with complete descriptions sell 40% faster than listings with sparse text. Buyers want confidence in what they are buying — a detailed description reduces questions, reduces returns, and increases trust.' },
      { type: 'p', text: 'The hashtags also matter. Vinted buyers browse by tag as much as by search. Including #nike #hoodie #streetwear #red #medium puts your listing in front of buyers who are browsing, not just searching.' },
      { type: 'h2', text: 'Batch listing with AI' },
      { type: 'p', text: 'Vintify\'s AI writer works in batch mode too. Photograph 20 items, type a few keywords for each, and generate all 20 listings in under 5 minutes. What used to be a full evening of listing becomes a coffee break.' },
      { type: 'cta', text: 'Take listing photos that actually sell your items', href: '/blog/vinted-photos-that-sell' },
      { type: 'cta', text: 'Try Vintify\'s AI listing writer free for 7 days', href: '/pricing' },
    ],
  },
  {
    slug: 'vinted-shipping-guide',
    title: 'Vinted shipping explained: Evri, InPost, Yodel, and Royal Mail',
    excerpt: 'Every shipping option on Vinted, compared by cost, speed, and reliability. Plus how to track them all in one place.',
    date: '2025-07-21',
    readTime: '7 min read',
    category: 'Guides',
    keywords: ['vinted shipping guide', 'vinted shipping options UK', 'vinted evri shipping', 'vinted inpost lockers', 'vinted yodel shipping', 'vinted royal mail', 'vinted shipping labels', 'vinted shipping explained'],
    author: 'Vintify Team',
    image: 'https://images.pexels.com/photos/7844005/pexels-photo-7844005.jpeg?auto=compress&cs=tinysrgb&w=1200',
    imageAlt: 'Delivery courier holding a parcel',
    content: [
      { type: 'p', text: 'Shipping is where many Vinted sales go wrong. A buyer selects a courier, you print the label, and then... the parcel disappears into a black hole. Understanding how each courier works on Vinted helps you set expectations and avoid negative reviews.' },
      { type: 'h2', text: 'Evri (formerly Hermes)' },
      { type: 'p', text: 'Evri is the default shipping option on most Vinted listings. It is cheap (buyer pays £2.99-£3.49) and has the most drop-off points — over 7,500 Evri ParcelShops and lockers across the UK. Delivery takes 2-3 days.' },
      { type: 'p', text: 'The downside: Evri tracking can be unreliable. Parcels sometimes show "in transit" for days after delivery. Evri also has a higher rate of lost parcels than Royal Mail — roughly 1 in 200 compared to 1 in 500.' },
      { type: 'h2', text: 'InPost' },
      { type: 'p', text: 'InPost lockers are becoming the most popular option on Vinted. They are automated 24/7 — no queueing, no counter staff, no opening hours. You drop the parcel in a locker, the buyer collects from a locker near them. Delivery takes 1-2 days.' },
      { type: 'p', text: 'InPost is highly reliable — the automated system means fewer handling points and less chance of loss. The only limitation is locker availability in rural areas. Most urban and suburban locations have multiple InPost lockers within a mile.' },
      { type: 'h2', text: 'Yodel' },
      { type: 'p', text: 'Yodel is the budget option on Vinted — buyer pays around £2.50. Delivery takes 3-5 days, and tracking updates are slower than Evri. Yodel has improved significantly in recent years but still has the lowest reliability score of the four.' },
      { type: 'p', text: 'Use Yodel for low-value items where the buyer is price-sensitive. For items over £30, recommend InPost or Royal Mail for peace of mind.' },
      { type: 'h2', text: 'Royal Mail' },
      { type: 'p', text: 'Royal Mail is the premium option — buyer pays £4.99-£6.99 depending on size. Delivery is 1-2 days with Tracked 48 or next day with Tracked 24. Royal Mail has the best reliability and the most comprehensive tracking.' },
      { type: 'p', text: 'Royal Mail is the best choice for expensive items, fragile items, or time-sensitive sales. The higher cost deters some buyers, but the reliability is worth it for high-value transactions.' },
      { type: 'h2', text: 'Managing all your labels in one place' },
      { type: 'p', text: 'When you sell across multiple platforms or have 20+ items sold per week, tracking shipping labels becomes a full-time job. Vintify\'s Label Hub imports all your Vinted shipping labels into one dashboard — you see what needs to be posted, what is in transit, and what has been delivered, all without checking Vinted manually.' },
      { type: 'p', text: 'You can print labels in bulk, mark items as dispatched, and get alerts when a parcel has not been scanned after 48 hours — so you can chase the courier before the buyer opens a dispute.' },
      { type: 'cta', text: 'Just starting out? Read our complete Vinted beginner\'s guide', href: '/blog/how-to-sell-on-vinted-uk-beginners-guide' },
      { type: 'cta', text: 'Manage all your shipping labels in one place with Vintify', href: '/features/automation' },
    ],
  },
  {
    slug: 'tracking-profit-per-item',
    title: 'Why tracking profit per item is the most important metric',
    excerpt: 'Revenue is vanity, profit is sanity. Here\'s why knowing your true profit on every single item changes everything.',
    date: '2025-07-19',
    readTime: '4 min read',
    category: 'Accounting',
    keywords: ['vinted profit per item', 'vinted profit tracking', 'vinted reseller profit', 'how to calculate vinted profit', 'vinted profit margin', 'vinted reselling metrics', 'vinted business tracking'],
    author: 'Vintify Team',
    image: 'https://images.pexels.com/photos/7108044/pexels-photo-7108044.jpeg?auto=compress&cs=tinysrgb&w=1200',
    imageAlt: 'Laptop screen displaying financial graphs and charts',
    content: [
      { type: 'p', text: 'Most Vinted resellers know their revenue. "I made £800 this month." But revenue is not profit. If you spent £600 on inventory, £40 on packaging, and £20 on shipping, your profit is £140 — not £800. And if you value your time at £12/hour and spent 15 hours sourcing, listing, and shipping, your real profit is negative.' },
      { type: 'h2', text: 'The true cost of an item' },
      { type: 'p', text: 'Every item you sell has costs that eat into your profit:' },
      { type: 'ul', items: [
        'Cost of goods — what you paid for the item',
        'Vinted buyer fees — indirectly, they reduce what buyers will pay',
        'Shipping — if you absorb any shipping cost to stay competitive',
        'Packaging — poly bags, bubble wrap, tape, thank-you cards',
        'Sourcing time — travel costs and time spent hunting for stock',
        'Listing time — photographing, writing, and pricing each item',
        'Customer service time — answering messages and handling disputes',
      ]},
      { type: 'p', text: 'When you add all of these up, your £20 sale might have cost you £15 to deliver. That is £5 profit — not £20.' },
      { type: 'h2', text: 'Why per-item profit matters more than monthly profit' },
      { type: 'p', text: 'Monthly profit tells you whether your business is working. Per-item profit tells you which parts of your business are working. If you sell 50 items a month and your average profit per item is £4, you make £200. But if you can identify that Nike hoodies make you £12 profit while Primark dresses make you £1, you can focus on hoodies and triple your income.' },
      { type: 'p', text: 'Without per-item tracking, you are flying blind. You might think you are doing well because revenue is high, while quietly losing money on certain categories or brands.' },
      { type: 'h2', text: 'How Vintify calculates true profit' },
      { type: 'p', text: 'Vintify automatically calculates profit per item. When you log a sale, Vintify pulls in the sale price, deducts Vinted fees, shipping costs, and packaging (if you have set defaults). It also deducts the cost price you entered when you listed the item.' },
      { type: 'p', text: 'The result is a real-time dashboard showing your average profit per item, profit by brand, profit by category, and profit trends over time. You can see at a glance which brands are worth sourcing and which are dragging your average down.' },
      { type: 'h2', text: 'The 80/20 of reselling' },
      { type: 'p', text: 'In most reselling businesses, 20% of items generate 80% of profit. Per-item tracking reveals which items are in that 20% so you can double down on what works and stop wasting time on what does not.' },
      { type: 'p', text: 'This is the difference between treating reselling as a hobby and treating it as a business. Hobbies track revenue. Businesses track profit.' },
      { type: 'cta', text: 'Understand your Vinted tax obligations as a reseller', href: '/blog/vinted-tax-guide-uk-2025' },
      { type: 'cta', text: 'See how Vintify calculates true profit on every sale', href: '/features/accounting' },
    ],
  },
  {
    slug: 'how-to-sell-on-vinted-uk-beginners-guide',
    title: 'How to sell on Vinted UK: The complete beginner\'s guide for 2025',
    excerpt: 'Everything you need to start selling on Vinted UK — from creating your account and listing your first item to choosing shipping options and getting paid. No experience needed.',
    date: '2025-07-17',
    readTime: '9 min read',
    category: 'Guides',
    keywords: ['how to sell on vinted', 'vinted beginner guide', 'how to sell on vinted UK', 'vinted selling guide', 'start selling on vinted', 'vinted tutorial', 'vinted for beginners', 'how does vinted work'],
    author: 'Vintify Team',
    image: 'https://images.pexels.com/photos/6609229/pexels-photo-6609229.jpeg?auto=compress&cs=tinysrgb&w=1200',
    imageAlt: 'Woman shopping online with a laptop and phone',
    content: [
      { type: 'p', text: 'Vinted is the UK\'s fastest-growing second-hand fashion platform, with over 17 million users. It costs nothing to list, nothing to sell, and you keep 100% of your earnings. If you have clothes in your wardrobe you never wear, or you want to start a reselling side hustle, this guide walks you through every step.' },
      { type: 'h2', text: 'Step 1: Create your Vinted account' },
      { type: 'p', text: 'Download the Vinted app (iOS or Android) or go to vinted.co.uk. Sign up with your email, Google, or Apple account. You will need to verify your identity — Vinted requires a photo of your face to prevent fake accounts. This takes 30 seconds and is mandatory before you can list anything.' },
      { type: 'p', text: 'Choose your username carefully. Buyers will see it on every listing and review. Something professional and memorable works best — avoid random numbers that make you look like a bot.' },
      { type: 'h2', text: 'Step 2: Photograph your items' },
      { type: 'p', text: 'Photos are the single most important factor in selling on Vinted. The platform is visual — buyers scroll through image-led feeds and make snap judgements. A good photo can be the difference between a sale in 2 hours and a listing that sits for 3 months.' },
      { type: 'ul', items: [
        'Use natural daylight — take photos near a window during the day, never with flash',
        'Use a clean, uncluttered background — a plain wall or white sheet works perfectly',
        'Lay items flat or hang them — never scrunch clothes up, buyers want to see the shape and design',
        'Take 5-8 photos per item: front, back, close-up of any labels, close-up of any defects, and a styling shot if possible',
        'Use all 20 photo slots for expensive items — the more detail, the more buyer confidence',
      ]},
      { type: 'h2', text: 'Step 3: Write your listing' },
      { type: 'p', text: 'Vinted search is keyword-based, so your title and description matter. A good title includes brand, item type, colour, size, and condition. For example: "Nike Tech Fleece Hoodie Red Size M Excellent Condition" will rank far better than "Nike hoodie".' },
      { type: 'p', text: 'In the description, include measurements (pit-to-pit, length), material composition, and any flaws. Being honest about defects builds trust and reduces returns. Add relevant hashtags like #nike #hoodie #streetwear #red to appear in tag-based browsing.' },
      { type: 'p', text: 'Choose the right category and sub-category. A vintage Levi\'s jacket listed under "Coats" instead of "Denim jackets" will miss the most relevant searches. Take 10 extra seconds to drill down to the correct sub-category.' },
      { type: 'h2', text: 'Step 4: Set your price' },
      { type: 'p', text: 'Search Vinted for similar items (same brand, size, colour) and note the asking prices. Price 5-10% below the median for a quick sale, or at the median if you are willing to wait. Always leave 15-20% negotiation margin — UK buyers expect to make offers.' },
      { type: 'p', text: 'Use .99 pricing. £14.99 outperforms £15 because it falls into the "under £15" filter. Vinted buyers browse with price filters more than any other filter type.' },
      { type: 'h2', text: 'Step 5: Choose shipping options' },
      { type: 'p', text: 'Vinted offers four main shipping options in the UK: Evri, InPost, Yodel, and Royal Mail. The buyer chooses and pays for shipping at checkout — you just print the label. Enable all available options to maximise your buyer pool.' },
      { type: 'p', text: 'InPost lockers are the most popular choice in 2025 — they are automated, 24/7, and highly reliable. Evri has the most drop-off points. Royal Mail is best for expensive items. See our complete Vinted shipping guide for a detailed comparison.' },
      { type: 'h2', text: 'Step 6: Get paid' },
      { type: 'p', text: 'When a buyer purchases your item, the money is held by Vinted until the buyer confirms delivery. Once confirmed (or after 2 days of delivery with no dispute), the funds appear in your Vinted Balance. You can withdraw to your bank account or PayPal at any time — there are no withdrawal fees.' },
      { type: 'h2', text: 'Tips for selling faster' },
      { type: 'ul', items: [
        'List consistently — Vinted\'s algorithm rewards active sellers. 10 items per day outperforms 50 items once a week',
        'Bump stale listings daily — it is free and pushes your items back up in search results',
        'Respond to messages within 1 hour — buyers compare 3-5 sellers and usually pick whoever replies first',
        'Send offers to people who favourite your items — a 10-15% discount often closes the sale',
        'List on Sunday evenings (7-10pm) — this is the strongest engagement window of the UK week',
      ]},
      { type: 'p', text: 'Once you are selling regularly, tools like Vintify can automate the repetitive parts — relisting, price drops, shipping label management, and profit tracking — so you can focus on sourcing and growing your business.' },
      { type: 'cta', text: 'Compare Vinted with Depop and eBay for resellers', href: '/blog/vinted-vs-depop-vs-ebay' },
      { type: 'cta', text: 'Learn how to price your Vinted items for maximum profit', href: '/blog/how-to-price-vinted-items' },
    ],
  },
  {
    slug: 'what-sells-best-on-vinted-uk',
    title: 'What sells best on Vinted UK: Top brands, categories, and items in 2025',
    excerpt: 'The brands, categories, and item types that consistently sell fast on Vinted UK — based on real seller data and buyer search trends.',
    date: '2025-07-15',
    readTime: '7 min read',
    category: 'Growth',
    keywords: ['what sells best on vinted', 'best brands to sell on vinted', 'vinted best selling items', 'what to sell on vinted UK', 'vinted top brands', 'vinted popular categories', 'vinted reselling niches'],
    author: 'Vintify Team',
    image: 'https://images.pexels.com/photos/6540983/pexels-photo-6540983.jpeg?auto=compress&cs=tinysrgb&w=1200',
    imageAlt: 'Blue and white Nike sneakers with yellow branding',
    content: [
      { type: 'p', text: 'Not everything sells equally on Vinted. Some brands fly off the shelves in hours, while others sit for months with zero interest. Knowing what sells best — and what to avoid — is the single biggest advantage you can give yourself as a reseller.' },
      { type: 'h2', text: 'The best-selling brands on Vinted UK' },
      { type: 'p', text: 'Based on seller data and buyer search trends, these brands consistently perform well on Vinted UK:' },
      { type: 'ul', items: [
        'Nike — the most searched brand on Vinted UK. Tech Fleece hoodies, Air Max trainers, and tracksuits sell fastest',
        'Adidas — Originals, Sambas, and Gazelles are in high demand. Streetwear pieces sell within days',
        'The North Face — puffer jackets and fleeces sell year-round, with peak demand October-February',
        'Lululemon — leggings, jackets, and bags. Anything Lululemon sells fast at the right price',
        'Levi\'s — denim jackets and 501 jeans are Vinted staples. Vintage Levi\'s commands premium prices',
        'Zara — fast fashion in good condition sells quickly, especially recent collections',
        'Ralph Lauren — consistent demand across men\'s, women\'s, and kids\'',
        'Barbour — wax jackets can double or triple your money in good condition',
        'Patagonia — fleeces and outdoor gear have a dedicated following',
        'Stone Island and Carhartt WIP — streetwear with strong resale value',
      ]},
      { type: 'h2', text: 'The best-selling categories' },
      { type: 'p', text: 'Women\'s clothing is the dominant category on Vinted UK — it has the most buyers, the most listings, and the most profit opportunity. Within women\'s clothing, these sub-categories perform best:' },
      { type: 'ul', items: [
        'Activewear and gym wear — Lululemon, Gymshark, Nike Pro',
        'Denim — Levi\'s, Wrangler, and premium denim brands',
        'Knitwear — cashmere and wool jumpers in autumn and winter',
        'Going-out tops and dresses — especially sequin, satin, and party wear',
        'Vintage and Y2K — huge demand from younger buyers for 90s and 2000s pieces',
      ]},
      { type: 'p', text: 'Men\'s clothing gets less attention from sellers, which means less competition. Streetwear (Nike, Adidas, Carhartt), vintage jackets, and branded trainers sell well. Men are shopping on Vinted more than ever, but fewer sellers target them.' },
      { type: 'p', text: 'Kids\' clothing is a steady market — parents buy in bundles, and brands like Boden, Joules, and Mini Boden have loyal followings. Sizes 0-10 sell best.' },
      { type: 'h2', text: 'What to avoid selling' },
      { type: 'ul', items: [
        'Primark, George, and basic H&M — sells, but for very little. Only worth listing in like-new condition',
        'River Island and Boohoo — lots of supply, low prices, low demand',
        'Damaged or stained items — buyers on Vinted expect wearable condition',
        'Very heavy or large items — shipping costs make them uneconomical',
        'Items priced under £3 — the time and effort of listing, packing, and posting is not worth the return',
      ]},
      { type: 'h2', text: 'The sweet spot for pricing' },
      { type: 'p', text: 'Items in the £8-£30 range offer the best balance of sell-through rate and profit per item. Below £8, the effort per sale is too high. Above £30, buyers become more cautious and sales slow down unless the brand is highly desirable.' },
      { type: 'p', text: 'For high-value items (£50+), invest in excellent photos, detailed descriptions, and consider offering Royal Mail shipping for buyer confidence. See our guide on how to price Vinted items for a complete pricing framework.' },
      { type: 'h2', text: 'Seasonal trends' },
      { type: 'p', text: 'Timing matters as much as brand and category. Winter coats and knitwear sell October-February. Swimwear and summer dresses sell May-August. Party wear spikes in December. Listing items in the right season can double your sell-through rate.' },
      { type: 'p', text: 'Off-season buying is where smart resellers make their margin. Buy winter coats in April when nobody wants them. Buy swimwear in October. List them when demand returns and sell at full price.' },
      { type: 'cta', text: 'How to price your Vinted items for maximum profit', href: '/blog/how-to-price-vinted-items' },
      { type: 'cta', text: 'Find profitable stock with our sourcing guide', href: '/blog/how-to-source-clothes-for-vinted' },
    ],
  },
  {
    slug: 'vinted-photos-that-sell',
    title: 'Vinted photos that sell: How to take listing photos that convert buyers',
    excerpt: 'Bad photos are the #1 reason items do not sell on Vinted. Here is exactly how to take photos that make buyers click buy now instead of scrolling past.',
    date: '2025-07-13',
    readTime: '6 min read',
    category: 'Growth',
    keywords: ['vinted photos', 'vinted listing photos', 'how to take photos for vinted', 'vinted photography tips', 'vinted photo guide', 'vinted listing tips', 'vinted photos that sell'],
    author: 'Vintify Team',
    image: 'https://images.pexels.com/photos/593319/pexels-photo-593319.jpeg?auto=compress&cs=tinysrgb&w=1200',
    imageAlt: 'Flat lay photography setup with phone and camera on table',
    content: [
      { type: 'p', text: 'Vinted is a visual platform. Buyers scroll through a feed of images and make split-second decisions. Your photo is your shop window — if it looks unappealing, buyers will not even read your title or price. Good photos can increase your sell-through rate by 70% or more.' },
      { type: 'h2', text: 'Lighting: the make-or-break factor' },
      { type: 'p', text: 'Natural daylight is non-negotiable. Take your photos during the day, near a window. Overcast days actually produce the best light — the clouds act as a giant softbox, giving even, shadow-free illumination. Never use flash — it distorts colours and creates harsh shadows that make clothes look cheap.' },
      { type: 'p', text: 'If you sell at night or in a dark flat, invest in a cheap ring light or a daylight-balanced LED panel. A £15 ring light from Amazon will dramatically improve your photos compared to a yellow ceiling bulb.' },
      { type: 'h2', text: 'How to position your items' },
      { type: 'p', text: 'There are two approaches that work well on Vinted:' },
      { type: 'ul', items: [
        'Flat lay — lay the item on a clean, contrasting surface (white sheet, light wood table). Smooth out wrinkles and arrange the item so its shape is visible. This works best for t-shirts, jumpers, and lightweight items',
        'Hanging — hang the item on a plain hanger against a white or light wall. This works best for jackets, dresses, and items where the drape and fit matter',
      ]},
      { type: 'p', text: 'Never scrunch clothes up or photograph them on the floor. One of the most upvoted posts on the Vinted subreddit is literally just a complaint about sellers bunching up t-shirts so you cannot see the design. Lay items flat or hang them.' },
      { type: 'h2', text: 'The essential photo set' },
      { type: 'p', text: 'For every item, take at minimum these 5 photos:' },
      { type: 'ul', items: [
        'Front view — the main shot, fully visible, good lighting',
        'Back view — shows the back design, labels, or any details',
        'Close-up of the brand label — proves authenticity',
        'Close-up of the size label — saves buyers asking "what size is this?"',
        'Close-up of any defects — be honest about marks, holes, or wear',
      ]},
      { type: 'p', text: 'For expensive items, add: material texture close-up, inside lining, tag/price tag if NWT, and a styled outfit shot showing how the item looks worn. Use all 20 photo slots — the more detail, the more buyer confidence.' },
      { type: 'h2', text: 'Background and composition' },
      { type: 'p', text: 'Keep your background clean and consistent. A messy bedroom in the background distracts from the item and looks unprofessional. A plain white wall, a white sheet, or a light wooden floor all work well.' },
      { type: 'p', text: 'Consistency across your listings builds trust. If all your photos have the same background and lighting, buyers recognise your items in the feed and are more likely to click. It looks like a real shop, not a random wardrobe clearout.' },
      { type: 'h2', text: 'Common photo mistakes that kill sales' },
      { type: 'ul', items: [
        'Dark or yellow lighting — makes colours look wrong and items look old',
        'Creased, wrinkled items — iron before photographing, wrinkles look like damage',
        'Cluttered backgrounds — buyers cannot focus on the item',
        'Only one photo — buyers assume you are hiding something',
        'Photos of the item on your body — Vinted buyers want to see the item, not the seller',
        'Screenshots of product photos — buyers want to see the actual item they will receive',
      ]},
      { type: 'h2', text: 'Editing: less is more' },
      { type: 'p', text: 'Light editing is fine — adjusting brightness, contrast, and cropping. But do not use filters that change the colour. If a buyer receives a navy jumper that looked black in your photo, they will open a dispute. Accurate colours build trust and reduce returns.' },
      { type: 'p', text: 'Most modern phone cameras are good enough. You do not need a DSLR. The Vinted app also has a built-in background removal tool for some categories, which can help your listing stand out in the feed.' },
      { type: 'cta', text: 'Write better listings with AI — try Vintify free for 7 days', href: '/pricing' },
      { type: 'cta', text: 'How to sell on Vinted UK: the complete beginner\'s guide', href: '/blog/how-to-sell-on-vinted-uk-beginners-guide' },
    ],
  },
  {
    slug: 'vinted-relisting-strategy',
    title: 'Vinted relisting strategy: When and how to refresh your listings',
    excerpt: 'Vinted\'s algorithm favours fresh listings. Items older than 7 days are buried pages deep. Here is how to relist strategically to maximise visibility and sales.',
    date: '2025-07-12',
    readTime: '5 min read',
    category: 'Growth',
    keywords: ['vinted relisting', 'vinted relist strategy', 'how to relist on vinted', 'vinted bump listings', 'vinted algorithm', 'vinted listing refresh', 'vinted boost listings'],
    author: 'Vintify Team',
    image: 'https://images.pexels.com/photos/6476808/pexels-photo-6476808.jpeg?auto=compress&cs=tinysrgb&w=1200',
    imageAlt: 'Business plan and schedule written in a notebook on a desk',
    content: [
      { type: 'p', text: 'The single biggest miss on Vinted is not relisting. Vinted\'s algorithm favours fresh listings — an item posted 7 days ago is already 5 pages deep in search results. Relisting brings it back to the top, for free. Yet most sellers list once and hope.' },
      { type: 'h2', text: 'Why Vinted buries old listings' },
      { type: 'p', text: 'Vinted wants buyers to see fresh inventory. When a buyer searches "Nike hoodie," the algorithm prioritises listings posted in the last 48 hours. After a week, your listing is competing with hundreds of newer posts and barely visible. After a month, it is effectively invisible.' },
      { type: 'p', text: 'This is not a bug — it is the platform\'s design. It rewards active sellers who list consistently and penalises those who batch-list once and disappear.' },
      { type: 'h2', text: 'The free bump: use it daily' },
      { type: 'p', text: 'Vinted offers a free "Bump" feature on every listing. You can bump each listing once per day for free. Bumping pushes your item back up in search results. It takes 2 seconds per item and costs nothing.' },
      { type: 'p', text: 'If you have 30 active listings, bumping all of them takes about 2 minutes. Do it every morning while having coffee. This alone can double your visibility without relisting.' },
      { type: 'h2', text: 'When to relist (not just bump)' },
      { type: 'p', text: 'Bumping helps, but relisting is more powerful. Relisting means deleting the old listing and creating a new one with the same item. The new listing gets the full "fresh listing" algorithm boost — appearing at the top of search and in buyers\' feeds.' },
      { type: 'p', text: 'Relist items that have not sold after:' },
      { type: 'ul', items: [
        '7 days — if the item is in a popular category (women\'s clothing, Nike, Zara)',
        '14 days — for mid-demand items (men\'s clothing, kids\' clothing)',
        '30 days — for niche items (vintage, collectables, unusual sizes)',
      ]},
      { type: 'p', text: 'When relisting, take the opportunity to improve. Use better photos, adjust the price down 5-10%, and refine your title with more keywords. A relisted item with improved photos and a lower price often sells within hours.' },
      { type: 'h2', text: 'The optimal listing schedule' },
      { type: 'p', text: 'The best Vinted sellers do not list everything at once. They spread listings across the week to maintain consistent visibility:' },
      { type: 'ul', items: [
        'Sunday evening (7-10pm) — list 10-15 new items. This is the strongest engagement window of the UK week',
        'Wednesday afternoon — relist anything older than 4 days. Catch the mid-week work-from-home shoppers',
        'Friday 6pm — message all favouriters with a 10-15% discount offer. Friday evening buys are impulse buys',
        'Saturday morning — reply to all overnight messages and bump all active listings',
      ]},
      { type: 'h2', text: 'Paid boosting: is it worth it?' },
      { type: 'p', text: 'Vinted offers paid "Boost" options that push your listing to more buyers for a set period. The fee varies based on your item\'s price and the boost duration. For items under £15, paid boosting is rarely worth it — the fee eats too much of your margin. For items over £30, a 3-day boost can be worthwhile if the item is desirable and well-photographed.' },
      { type: 'h2', text: 'Automating relists' },
      { type: 'p', text: 'When you have 50+ active listings, manually bumping and relisting becomes a daily chore. Vintify automates the entire process — it bumps listings on schedule, flags items that need relisting, and can auto-relist with refreshed photos and adjusted prices. You set the rules once, and Vintify handles the rest.' },
      { type: 'p', text: 'This is how serious resellers scale — they stop doing manual platform tasks and focus on sourcing, while their tools keep their existing inventory visible.' },
      { type: 'cta', text: 'Automate relisting and price drops with Vintify\'s growth bot', href: '/features/growth-bot' },
      { type: 'cta', text: 'Learn what sells best on Vinted UK', href: '/blog/what-sells-best-on-vinted-uk' },
    ],
  },
  {
    slug: 'how-to-source-clothes-for-vinted',
    title: 'How to source clothes for Vinted reselling: Charity shops, car boots, and wholesale',
    excerpt: 'Where to find stock that actually sells on Vinted — charity shop strategies, car boot sale tips, wholesale options, and how to calculate your cost-per-item target.',
    date: '2025-07-11',
    readTime: '8 min read',
    category: 'Guides',
    keywords: ['how to source clothes for vinted', 'vinted sourcing', 'charity shop reselling', 'car boot sale reselling', 'vinted wholesale', 'where to buy stock for vinted', 'vinted reseller sourcing', 'thrifting for resale'],
    author: 'Vintify Team',
    image: 'https://images.pexels.com/photos/6994939/pexels-photo-6994939.jpeg?auto=compress&cs=tinysrgb&w=1200',
    imageAlt: 'Volunteers organising clothes in a thrift store',
    content: [
      { type: 'p', text: 'Sourcing is the foundation of every reselling business. You cannot sell well what you bought badly. The margin is made at the buying stage, not the selling stage. This guide covers the four main sourcing channels for Vinted resellers in the UK and how to build a sourcing system that consistently finds profitable stock.' },
      { type: 'h2', text: 'Channel 1: Charity shops' },
      { type: 'p', text: 'Charity shops are the bread and butter of UK resellers. They are cheap, everywhere, and constantly restocked. The average price for a branded item in a UK charity shop is £3-£8, which means you can sell it on Vinted for £15-£30 and make 3-5x your money.' },
      { type: 'p', text: 'Strategy matters. Do not walk into one charity shop and hope. Plan a route of 5-10 shops in an affluent area — wealthy neighbourhoods donate better quality, better brands. Visit regularly (twice a week) and build relationships with staff. Many charity shops put good donations out on specific days — find out when and be there first.' },
      { type: 'ul', items: [
        'Target affluent areas — better brands, better condition, higher donations',
        'Visit on restock days — ask staff when new stock goes out',
        'Look for branded items only — Nike, Levi\'s, Ralph Lauren, Barbour, Lululemon',
        'Check the menswear section — less competition from other resellers',
        'Check the kids\' section — Boden, Joules, and Mini Boden are regularly underpriced',
      ]},
      { type: 'h2', text: 'Channel 2: Car boot sales' },
      { type: 'p', text: 'Car boot sales are the cheapest sourcing channel in the UK. Prices are often £1-£3 per item, and you can negotiate bulk discounts. The best car boot sales run Sunday mornings from April to October.' },
      { type: 'p', text: 'Arrive early — the best stock goes in the first hour. Bring cash in small denominations (£1 and £2 coins) so you can buy quickly without waiting for change. Look for sellers with rails of clothes — they are usually clearing wardrobes and will accept bulk offers.' },
      { type: 'p', text: 'The downside of car boot sales is volume and quality. You will look at 200 items to find 10 worth buying. But at £1-£2 each, those 10 items can generate £150-£300 in Vinted sales.' },
      { type: 'h2', text: 'Channel 3: Wholesale and clearance' },
      { type: 'p', text: 'If you want to scale beyond individual item sourcing, wholesale is the next step. UK wholesale options for Vinted resellers include:' },
      { type: 'ul', items: [
        'Vintage wholesale kilo sales — buy clothing by weight (£10-£15 per kg). Available in major cities',
        'Charity shop clearance — some charity chains sell unsold stock in bulk at £1-£2 per item',
        'eBay job lots — buy clearance or returned stock in bundles, sort and resell individually on Vinted',
        'Liquidation stock — ex-retail stock sold in pallets, but quality varies significantly',
      ]},
      { type: 'p', text: 'Wholesale works best when you have a specific niche. If you know vintage Levi\'s sell well, buying a kilo of vintage denim and listing 20 pairs is efficient. If you buy random mixed kilos, half the stock may be unsellable.' },
      { type: 'h2', text: 'Channel 4: Sourcing on Vinted itself' },
      { type: 'p', text: 'Some resellers source directly from Vinted — buying underpriced items and relisting them with better photos, better titles, and better pricing. This is called "Vinted flipping" and it works, but margins are thinner and competition is increasing.' },
      { type: 'p', text: 'To find underpriced items, search for misspelled brand names ("Addidas" instead of "Adidas"), items listed in wrong categories, and items with poor photos. These listings get less traffic, so you can buy below market price. Improve the listing and resell at the true market value.' },
      { type: 'h2', text: 'Setting your cost-per-item target' },
      { type: 'p', text: 'Before you source, decide your target margin. A good rule of thumb: aim for at least 3x return on cost. If you buy a jacket for £8, it should sell for £24+ after fees. This gives you room for price drops, shipping, and still leaves profit.' },
      { type: 'p', text: 'Track every sourcing trip in Vintify — log what you bought, where, how much, and what it sold for. Over time, you will see which charity shops, car boots, and wholesale suppliers give you the best return on investment. Data beats gut feeling every time.' },
      { type: 'cta', text: 'Track profit per item and sourcing ROI with Vintify', href: '/features/accounting' },
      { type: 'cta', text: 'Read our complete Vinted tax guide for UK resellers', href: '/blog/vinted-tax-guide-uk-2025' },
    ],
  },
  {
    slug: 'vinted-pro-seller-guide',
    title: 'Vinted Pro Seller: Should you register as a business seller in 2025?',
    excerpt: 'Vinted Pro lets you sell as a registered business on Vinted. Here is what it costs, what you get, and whether it is worth switching from a personal account.',
    date: '2025-07-10',
    readTime: '6 min read',
    category: 'Guides',
    keywords: ['vinted pro seller', 'vinted pro account', 'vinted business seller', 'vinted pro vs personal', 'vinted pro UK', 'vinted registered business', 'vinted sole trader'],
    author: 'Vintify Team',
    image: 'https://images.pexels.com/photos/5685961/pexels-photo-5685961.jpeg?auto=compress&cs=tinysrgb&w=1200',
    imageAlt: 'Businesswoman working on a laptop in an office',
    content: [
      { type: 'p', text: 'Vinted launched Pro Seller accounts in the UK to let registered businesses sell on the platform with proper consumer protections. If you are selling to make a profit — not just clearing your wardrobe — you may need to register as a Pro Seller. This guide explains what Pro Seller is, what it costs, and whether you should make the switch.' },
      { type: 'h2', text: 'What is a Vinted Pro Seller?' },
      { type: 'p', text: 'A Pro Seller is someone registered as a sole trader, company, or non-profit who sells on Vinted as a business. Pro Sellers are identified by a "Pro" tag next to their name and listings. They must comply with consumer protection laws, including offering returns and providing specific information on each listing.' },
      { type: 'p', text: 'If you are buying items specifically to resell on Vinted for profit, you are legally a business seller — not a casual seller. Vinted\'s terms require you to register as Pro if this is the case. HMRC also expects you to register as self-employed if you exceed the £1,000 trading allowance.' },
      { type: 'h2', text: 'Who needs to register as Pro?' },
      { type: 'p', text: 'You must register as a Pro Seller if:' },
      { type: 'ul', items: [
        'You buy items specifically to resell for profit (sourcing from charity shops, car boots, wholesale)',
        'You make items to sell (handmade, upcycled, customised)',
        'You sell regularly and systematically (not just occasional wardrobe clearouts)',
        'Your total sales exceed £1,000 per tax year (the HMRC trading allowance threshold)',
      ]},
      { type: 'p', text: 'You do NOT need to register as Pro if you are casually selling your own used clothes and occasionally clearing your wardrobe. Personal sellers have no obligation to register.' },
      { type: 'h2', text: 'What Pro Sellers must do' },
      { type: 'p', text: 'Pro Sellers have additional obligations compared to personal sellers:' },
      { type: 'ul', items: [
        'Provide business contact information on your profile',
        'Comply with the Consumer Rights Act — items must be as described, of satisfactory quality, and fit for purpose',
        'Offer a 14-day return policy for online sales (Distance Selling Regulations)',
        'Include mandatory information on listings: price, condition, your identity, delivery method, and return rights',
        'Register for Self Assessment with HMRC if you exceed the £1,000 trading allowance',
      ]},
      { type: 'h2', text: 'Benefits of being a Pro Seller' },
      { type: 'p', text: 'Despite the extra obligations, there are real benefits to selling as Pro:' },
      { type: 'ul', items: [
        'The "Pro" badge builds buyer trust — buyers know they are buying from a legitimate business with consumer protections',
        'You can set your own additional policies (shipping, returns, custom terms)',
        'Vinted provides standard terms of sale that already include legally required information',
        'You are compliant with both Vinted\'s terms and UK law — no risk of account suspension for undeclared selling',
        'You can claim VAT input tax if you are VAT-registered (sales under the VAT threshold are not subject to VAT)',
      ]},
      { type: 'h2', text: 'Pro Seller vs personal seller: the cost comparison' },
      { type: 'p', text: 'Vinted does not charge Pro Sellers additional fees for listing or selling. The fee structure is the same as personal sellers — zero seller fees. The buyer pays a protection fee and shipping. The main cost of being a Pro Seller is the administrative burden: registering as self-employed with HMRC, filing a Self Assessment tax return, and complying with consumer protection law.' },
      { type: 'p', text: 'If you are already registered as self-employed and filing Self Assessment, the additional overhead of being a Pro Seller is minimal. If you are not yet registered, see our Vinted tax guide for step-by-step instructions.' },
      { type: 'h2', text: 'Should you switch?' },
      { type: 'p', text: 'If you are sourcing stock to resell, the answer is yes — you should register as Pro. It is a legal requirement, and the trust badge helps sales. The administrative work is a one-time setup, and tools like Vintify handle the ongoing tracking and reporting.' },
      { type: 'p', text: 'If you are only selling your own wardrobe clearouts, stay as a personal seller. You do not need Pro, and you do not need to register with HMRC — as long as your total sales stay under £1,000 per tax year.' },
      { type: 'p', text: 'The grey area is people who start as casual sellers and gradually become business sellers without realising it. If you are buying from charity shops to resell, you crossed that line. Register as Pro and register with HMRC. It is simpler than dealing with a tax investigation later.' },
      { type: 'cta', text: 'Read our complete Vinted tax guide for UK resellers', href: '/blog/vinted-tax-guide-uk-2025' },
      { type: 'cta', text: 'Generate HMRC-ready tax reports with Vintify', href: '/features/accounting' },
    ],
  },
];

export function getPostBySlug(slug) {
  return POSTS.find(p => p.slug === slug);
}

export function getAllSlugs() {
  return POSTS.map(p => p.slug);
}
